# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb2d518908a8ee0f30cc7367e0f602cc906eb1dd8e384be881e18ec7c6e209058c80932ac0bb76ae13dd575d7784edf8643da63bcc877319d2addea3d7cef14a

test:
  secret_key_base: 37168ca3a52bb2760739bf0acd4b85c4451bd01adcb3a46547d5363d52ac80e3beb4dc9e853b570d21783e8671d4b526f856a0d0789159a2f53ecd7f32e17046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
